/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.GameVersion;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GameVersionRecord extends UpdatableRecordImpl<GameVersionRecord> implements Record5<Long, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 1754389765;

    /**
     * Setter for <code>diluv.GAME_VERSION.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.GAME_VERSION.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.GAME_VERSION.VERSION</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.GAME_VERSION.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.GAME_VERSION.WEBSITE</code>.
     */
    public void setWebsite(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.GAME_VERSION.WEBSITE</code>.
     */
    public String getWebsite() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.GAME_VERSION.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.GAME_VERSION.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.GAME_VERSION.GAME_ID</code>.
     */
    public void setGameId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.GAME_VERSION.GAME_ID</code>.
     */
    public Long getGameId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return GameVersion.GAME_VERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GameVersion.GAME_VERSION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GameVersion.GAME_VERSION.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return GameVersion.GAME_VERSION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return GameVersion.GAME_VERSION.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord value2(String value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord value3(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord value5(Long value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersionRecord values(Long value1, String value2, String value3, Timestamp value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameVersionRecord
     */
    public GameVersionRecord() {
        super(GameVersion.GAME_VERSION);
    }

    /**
     * Create a detached, initialised GameVersionRecord
     */
    public GameVersionRecord(Long id, String version, String website, Timestamp createdAt, Long gameId) {
        super(GameVersion.GAME_VERSION);

        set(0, id);
        set(1, version);
        set(2, website);
        set(3, createdAt);
        set(4, gameId);
    }
}
