/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectFileProcessing;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileProcessingRecord extends UpdatableRecordImpl<ProjectFileProcessingRecord> implements Record3<Long, Integer, Timestamp> {

    private static final long serialVersionUID = 773559454;

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS_ID</code>.
     */
    public void setStatusId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS_ID</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Integer, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Integer, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value1(Long value) {
        setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value2(Integer value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord values(Long value1, Integer value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord() {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);
    }

    /**
     * Create a detached, initialised ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord(Long projectFileId, Integer statusId, Timestamp createdAt) {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);

        set(0, projectFileId);
        set(1, statusId);
        set(2, createdAt);
    }
}
