/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectMember;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectMemberRecord extends UpdatableRecordImpl<ProjectMemberRecord> implements Record6<Long, String, Integer, Timestamp, Long, Long> {

    private static final long serialVersionUID = -805315362;

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.ROLE</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.ROLE</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.PERMISSION</code>.
     */
    public void setPermission(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.PERMISSION</code>.
     */
    public Integer getPermission() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.PROJECT_ID</code>.
     */
    public void setProjectId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.PROJECT_ID</code>.
     */
    public Long getProjectId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT_MEMBER.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_MEMBER.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Integer, Timestamp, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Integer, Timestamp, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectMember.PROJECT_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectMember.PROJECT_MEMBER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ProjectMember.PROJECT_MEMBER.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProjectMember.PROJECT_MEMBER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProjectMember.PROJECT_MEMBER.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ProjectMember.PROJECT_MEMBER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value2(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value3(Integer value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value5(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord value6(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMemberRecord values(Long value1, String value2, Integer value3, Timestamp value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectMemberRecord
     */
    public ProjectMemberRecord() {
        super(ProjectMember.PROJECT_MEMBER);
    }

    /**
     * Create a detached, initialised ProjectMemberRecord
     */
    public ProjectMemberRecord(Long id, String role, Integer permission, Timestamp createdAt, Long projectId, Long userId) {
        super(ProjectMember.PROJECT_MEMBER);

        set(0, id);
        set(1, role);
        set(2, permission);
        set(3, createdAt);
        set(4, projectId);
        set(5, userId);
    }
}
