/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectCategory;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectCategoryRecord extends UpdatableRecordImpl<ProjectCategoryRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -590663694;

    /**
     * Setter for <code>diluv.PROJECT_CATEGORY.PROJECT_ID</code>.
     */
    public void setProjectId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_CATEGORY.PROJECT_ID</code>.
     */
    public Long getProjectId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_CATEGORY.PROJECT_TYPE_CATEGORY_ID</code>.
     */
    public void setProjectTypeCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_CATEGORY.PROJECT_TYPE_CATEGORY_ID</code>.
     */
    public Long getProjectTypeCategoryId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectCategory.PROJECT_CATEGORY.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ProjectCategory.PROJECT_CATEGORY.PROJECT_TYPE_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getProjectTypeCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCategoryRecord value1(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCategoryRecord value2(Long value) {
        setProjectTypeCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCategoryRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectCategoryRecord
     */
    public ProjectCategoryRecord() {
        super(ProjectCategory.PROJECT_CATEGORY);
    }

    /**
     * Create a detached, initialised ProjectCategoryRecord
     */
    public ProjectCategoryRecord(Long projectId, Long projectTypeCategoryId) {
        super(ProjectCategory.PROJECT_CATEGORY);

        set(0, projectId);
        set(1, projectTypeCategoryId);
    }
}
