/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectComment;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectCommentRecord extends UpdatableRecordImpl<ProjectCommentRecord> implements Record7<Long, String, Timestamp, Timestamp, Long, Long, Long> {

    private static final long serialVersionUID = 1314024962;

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.MESSAGE</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.MESSAGE</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.PARENT_ID</code>.
     */
    public void setParentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.PARENT_ID</code>.
     */
    public Long getParentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.PROJECT_ID</code>.
     */
    public void setProjectId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.PROJECT_ID</code>.
     */
    public Long getProjectId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>diluv.PROJECT_COMMENT.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_COMMENT.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, Timestamp, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, Timestamp, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectComment.PROJECT_COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectComment.PROJECT_COMMENT.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ProjectComment.PROJECT_COMMENT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProjectComment.PROJECT_COMMENT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProjectComment.PROJECT_COMMENT.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ProjectComment.PROJECT_COMMENT.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ProjectComment.PROJECT_COMMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value2(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value5(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value6(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord value7(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectCommentRecord values(Long value1, String value2, Timestamp value3, Timestamp value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectCommentRecord
     */
    public ProjectCommentRecord() {
        super(ProjectComment.PROJECT_COMMENT);
    }

    /**
     * Create a detached, initialised ProjectCommentRecord
     */
    public ProjectCommentRecord(Long id, String message, Timestamp createdAt, Timestamp updatedAt, Long parentId, Long projectId, Long userId) {
        super(ProjectComment.PROJECT_COMMENT);

        set(0, id);
        set(1, message);
        set(2, createdAt);
        set(3, updatedAt);
        set(4, parentId);
        set(5, projectId);
        set(6, userId);
    }
}
