/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.UserBetaKey;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserBetaKeyRecord extends UpdatableRecordImpl<UserBetaKeyRecord> implements Record5<String, Boolean, Timestamp, Long, Long> {

    private static final long serialVersionUID = -2035341322;

    /**
     * Setter for <code>diluv.USER_BETA_KEY.BETA_KEY</code>.
     */
    public void setBetaKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.USER_BETA_KEY.BETA_KEY</code>.
     */
    public String getBetaKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>diluv.USER_BETA_KEY.VALID</code>.
     */
    public void setValid(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.USER_BETA_KEY.VALID</code>.
     */
    public Boolean getValid() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>diluv.USER_BETA_KEY.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.USER_BETA_KEY.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>diluv.USER_BETA_KEY.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.USER_BETA_KEY.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>diluv.USER_BETA_KEY.CREATION_USER_ID</code>.
     */
    public void setCreationUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.USER_BETA_KEY.CREATION_USER_ID</code>.
     */
    public Long getCreationUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Boolean, Timestamp, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Boolean, Timestamp, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserBetaKey.USER_BETA_KEY.BETA_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return UserBetaKey.USER_BETA_KEY.VALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserBetaKey.USER_BETA_KEY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return UserBetaKey.USER_BETA_KEY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return UserBetaKey.USER_BETA_KEY.CREATION_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBetaKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCreationUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord value1(String value) {
        setBetaKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord value2(Boolean value) {
        setValid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord value5(Long value) {
        setCreationUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBetaKeyRecord values(String value1, Boolean value2, Timestamp value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserBetaKeyRecord
     */
    public UserBetaKeyRecord() {
        super(UserBetaKey.USER_BETA_KEY);
    }

    /**
     * Create a detached, initialised UserBetaKeyRecord
     */
    public UserBetaKeyRecord(String betaKey, Boolean valid, Timestamp createdAt, Long userId, Long creationUserId) {
        super(UserBetaKey.USER_BETA_KEY);

        set(0, betaKey);
        set(1, valid);
        set(2, createdAt);
        set(3, userId);
        set(4, creationUserId);
    }
}
