/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models;


import com.diluv.api.models.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Diluv extends SchemaImpl {

    private static final long serialVersionUID = -1356800644;

    /**
     * The reference instance of <code>diluv</code>
     */
    public static final Diluv DILUV = new Diluv();

    /**
     * The table <code>diluv.analyticsAuthAccessToken</code>.
     */
    public final Analyticsauthaccesstoken ANALYTICSAUTHACCESSTOKEN = com.diluv.api.models.tables.Analyticsauthaccesstoken.ANALYTICSAUTHACCESSTOKEN;

    /**
     * The table <code>diluv.analyticsAuthMFAToken</code>.
     */
    public final Analyticsauthmfatoken ANALYTICSAUTHMFATOKEN = com.diluv.api.models.tables.Analyticsauthmfatoken.ANALYTICSAUTHMFATOKEN;

    /**
     * The table <code>diluv.analyticsBetaKey</code>.
     */
    public final Analyticsbetakey ANALYTICSBETAKEY = com.diluv.api.models.tables.Analyticsbetakey.ANALYTICSBETAKEY;

    /**
     * The table <code>diluv.authAccessToken</code>.
     */
    public final Authaccesstoken AUTHACCESSTOKEN = com.diluv.api.models.tables.Authaccesstoken.AUTHACCESSTOKEN;

    /**
     * The table <code>diluv.authMFAToken</code>.
     */
    public final Authmfatoken AUTHMFATOKEN = com.diluv.api.models.tables.Authmfatoken.AUTHMFATOKEN;

    /**
     * The table <code>diluv.game</code>.
     */
    public final Game GAME = com.diluv.api.models.tables.Game.GAME;

    /**
     * The table <code>diluv.gameVersion</code>.
     */
    public final Gameversion GAMEVERSION = com.diluv.api.models.tables.Gameversion.GAMEVERSION;

    /**
     * The table <code>diluv.project</code>.
     */
    public final Project PROJECT = com.diluv.api.models.tables.Project.PROJECT;

    /**
     * The table <code>diluv.projectCategory</code>.
     */
    public final Projectcategory PROJECTCATEGORY = com.diluv.api.models.tables.Projectcategory.PROJECTCATEGORY;

    /**
     * The table <code>diluv.projectComment</code>.
     */
    public final Projectcomment PROJECTCOMMENT = com.diluv.api.models.tables.Projectcomment.PROJECTCOMMENT;

    /**
     * The table <code>diluv.projectFile</code>.
     */
    public final Projectfile PROJECTFILE = com.diluv.api.models.tables.Projectfile.PROJECTFILE;

    /**
     * The table <code>diluv.projectFileGameVersion</code>.
     */
    public final Projectfilegameversion PROJECTFILEGAMEVERSION = com.diluv.api.models.tables.Projectfilegameversion.PROJECTFILEGAMEVERSION;

    /**
     * The table <code>diluv.projectFileProcessing</code>.
     */
    public final Projectfileprocessing PROJECTFILEPROCESSING = com.diluv.api.models.tables.Projectfileprocessing.PROJECTFILEPROCESSING;

    /**
     * The table <code>diluv.projectMember</code>.
     */
    public final Projectmember PROJECTMEMBER = com.diluv.api.models.tables.Projectmember.PROJECTMEMBER;

    /**
     * The table <code>diluv.projectType</code>.
     */
    public final Projecttype PROJECTTYPE = com.diluv.api.models.tables.Projecttype.PROJECTTYPE;

    /**
     * The table <code>diluv.projectTypeCategory</code>.
     */
    public final Projecttypecategory PROJECTTYPECATEGORY = com.diluv.api.models.tables.Projecttypecategory.PROJECTTYPECATEGORY;

    /**
     * The table <code>diluv.projectTypePermission</code>.
     */
    public final Projecttypepermission PROJECTTYPEPERMISSION = com.diluv.api.models.tables.Projecttypepermission.PROJECTTYPEPERMISSION;

    /**
     * The table <code>diluv.user</code>.
     */
    public final User USER = com.diluv.api.models.tables.User.USER;

    /**
     * The table <code>diluv.userBetaKey</code>.
     */
    public final Userbetakey USERBETAKEY = com.diluv.api.models.tables.Userbetakey.USERBETAKEY;

    /**
     * No further instances allowed
     */
    private Diluv() {
        super("diluv", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Analyticsauthaccesstoken.ANALYTICSAUTHACCESSTOKEN,
                Analyticsauthmfatoken.ANALYTICSAUTHMFATOKEN,
                Analyticsbetakey.ANALYTICSBETAKEY,
                Authaccesstoken.AUTHACCESSTOKEN,
                Authmfatoken.AUTHMFATOKEN,
                Game.GAME,
                Gameversion.GAMEVERSION,
                Project.PROJECT,
                Projectcategory.PROJECTCATEGORY,
                Projectcomment.PROJECTCOMMENT,
                Projectfile.PROJECTFILE,
                Projectfilegameversion.PROJECTFILEGAMEVERSION,
                Projectfileprocessing.PROJECTFILEPROCESSING,
                Projectmember.PROJECTMEMBER,
                Projecttype.PROJECTTYPE,
                Projecttypecategory.PROJECTTYPECATEGORY,
                Projecttypepermission.PROJECTTYPEPERMISSION,
                User.USER,
                Userbetakey.USERBETAKEY);
    }
}
