/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models;


import com.diluv.api.models.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in diluv
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>diluv.analyticsAuthAccessToken</code>.
     */
    public static final Analyticsauthaccesstoken ANALYTICSAUTHACCESSTOKEN = com.diluv.api.models.tables.Analyticsauthaccesstoken.ANALYTICSAUTHACCESSTOKEN;

    /**
     * The table <code>diluv.analyticsAuthMFAToken</code>.
     */
    public static final Analyticsauthmfatoken ANALYTICSAUTHMFATOKEN = com.diluv.api.models.tables.Analyticsauthmfatoken.ANALYTICSAUTHMFATOKEN;

    /**
     * The table <code>diluv.analyticsBetaKey</code>.
     */
    public static final Analyticsbetakey ANALYTICSBETAKEY = com.diluv.api.models.tables.Analyticsbetakey.ANALYTICSBETAKEY;

    /**
     * The table <code>diluv.authAccessToken</code>.
     */
    public static final Authaccesstoken AUTHACCESSTOKEN = com.diluv.api.models.tables.Authaccesstoken.AUTHACCESSTOKEN;

    /**
     * The table <code>diluv.authMFAToken</code>.
     */
    public static final Authmfatoken AUTHMFATOKEN = com.diluv.api.models.tables.Authmfatoken.AUTHMFATOKEN;

    /**
     * The table <code>diluv.game</code>.
     */
    public static final Game GAME = com.diluv.api.models.tables.Game.GAME;

    /**
     * The table <code>diluv.gameVersion</code>.
     */
    public static final Gameversion GAMEVERSION = com.diluv.api.models.tables.Gameversion.GAMEVERSION;

    /**
     * The table <code>diluv.project</code>.
     */
    public static final Project PROJECT = com.diluv.api.models.tables.Project.PROJECT;

    /**
     * The table <code>diluv.projectCategory</code>.
     */
    public static final Projectcategory PROJECTCATEGORY = com.diluv.api.models.tables.Projectcategory.PROJECTCATEGORY;

    /**
     * The table <code>diluv.projectComment</code>.
     */
    public static final Projectcomment PROJECTCOMMENT = com.diluv.api.models.tables.Projectcomment.PROJECTCOMMENT;

    /**
     * The table <code>diluv.projectFile</code>.
     */
    public static final Projectfile PROJECTFILE = com.diluv.api.models.tables.Projectfile.PROJECTFILE;

    /**
     * The table <code>diluv.projectFileGameVersion</code>.
     */
    public static final Projectfilegameversion PROJECTFILEGAMEVERSION = com.diluv.api.models.tables.Projectfilegameversion.PROJECTFILEGAMEVERSION;

    /**
     * The table <code>diluv.projectFileProcessing</code>.
     */
    public static final Projectfileprocessing PROJECTFILEPROCESSING = com.diluv.api.models.tables.Projectfileprocessing.PROJECTFILEPROCESSING;

    /**
     * The table <code>diluv.projectMember</code>.
     */
    public static final Projectmember PROJECTMEMBER = com.diluv.api.models.tables.Projectmember.PROJECTMEMBER;

    /**
     * The table <code>diluv.projectType</code>.
     */
    public static final Projecttype PROJECTTYPE = com.diluv.api.models.tables.Projecttype.PROJECTTYPE;

    /**
     * The table <code>diluv.projectTypeCategory</code>.
     */
    public static final Projecttypecategory PROJECTTYPECATEGORY = com.diluv.api.models.tables.Projecttypecategory.PROJECTTYPECATEGORY;

    /**
     * The table <code>diluv.user</code>.
     */
    public static final User USER = com.diluv.api.models.tables.User.USER;

    /**
     * The table <code>diluv.userBetaKey</code>.
     */
    public static final Userbetakey USERBETAKEY = com.diluv.api.models.tables.Userbetakey.USERBETAKEY;
}
