/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.AnalyticsAuthMfaTokenRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AnalyticsAuthMfaToken extends TableImpl<AnalyticsAuthMfaTokenRecord> {

    private static final long serialVersionUID = 1278487171;

    /**
     * The reference instance of <code>diluv.ANALYTICS_AUTH_MFA_TOKEN</code>
     */
    public static final AnalyticsAuthMfaToken ANALYTICS_AUTH_MFA_TOKEN = new AnalyticsAuthMfaToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnalyticsAuthMfaTokenRecord> getRecordType() {
        return AnalyticsAuthMfaTokenRecord.class;
    }

    /**
     * The column <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.ID</code>.
     */
    public final TableField<AnalyticsAuthMfaTokenRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.TOKEN</code>.
     */
    public final TableField<AnalyticsAuthMfaTokenRecord, String> TOKEN = createField("TOKEN", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

    /**
     * The column <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.CREATED_AT</code>.
     */
    public final TableField<AnalyticsAuthMfaTokenRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.USER_ID</code>.
     */
    public final TableField<AnalyticsAuthMfaTokenRecord, Long> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.ANALYTICS_AUTH_MFA_TOKEN</code> table reference
     */
    public AnalyticsAuthMfaToken() {
        this("ANALYTICS_AUTH_MFA_TOKEN", null);
    }

    /**
     * Create an aliased <code>diluv.ANALYTICS_AUTH_MFA_TOKEN</code> table reference
     */
    public AnalyticsAuthMfaToken(String alias) {
        this(alias, ANALYTICS_AUTH_MFA_TOKEN);
    }

    private AnalyticsAuthMfaToken(String alias, Table<AnalyticsAuthMfaTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private AnalyticsAuthMfaToken(String alias, Table<AnalyticsAuthMfaTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AnalyticsAuthMfaTokenRecord, Long> getIdentity() {
        return Keys.IDENTITY_ANALYTICS_AUTH_MFA_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AnalyticsAuthMfaTokenRecord> getPrimaryKey() {
        return Keys.KEY_ANALYTICS_AUTH_MFA_TOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AnalyticsAuthMfaTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<AnalyticsAuthMfaTokenRecord>>asList(Keys.KEY_ANALYTICS_AUTH_MFA_TOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AnalyticsAuthMfaTokenRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AnalyticsAuthMfaTokenRecord, ?>>asList(Keys.ANALYTICS_AUTH_MFA_TOKEN_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaToken as(String alias) {
        return new AnalyticsAuthMfaToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalyticsAuthMfaToken rename(String name) {
        return new AnalyticsAuthMfaToken(name, null);
    }
}
