/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.GameVersionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GameVersion extends TableImpl<GameVersionRecord> {

    private static final long serialVersionUID = -298096027;

    /**
     * The reference instance of <code>diluv.GAME_VERSION</code>
     */
    public static final GameVersion GAME_VERSION = new GameVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameVersionRecord> getRecordType() {
        return GameVersionRecord.class;
    }

    /**
     * The column <code>diluv.GAME_VERSION.ID</code>.
     */
    public final TableField<GameVersionRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.GAME_VERSION.VERSION</code>.
     */
    public final TableField<GameVersionRecord, String> VERSION = createField("VERSION", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>diluv.GAME_VERSION.WEBSITE</code>.
     */
    public final TableField<GameVersionRecord, String> WEBSITE = createField("WEBSITE", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * The column <code>diluv.GAME_VERSION.CREATED_AT</code>.
     */
    public final TableField<GameVersionRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>diluv.GAME_VERSION.GAME_ID</code>.
     */
    public final TableField<GameVersionRecord, Long> GAME_ID = createField("GAME_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.GAME_VERSION</code> table reference
     */
    public GameVersion() {
        this("GAME_VERSION", null);
    }

    /**
     * Create an aliased <code>diluv.GAME_VERSION</code> table reference
     */
    public GameVersion(String alias) {
        this(alias, GAME_VERSION);
    }

    private GameVersion(String alias, Table<GameVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private GameVersion(String alias, Table<GameVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GameVersionRecord, Long> getIdentity() {
        return Keys.IDENTITY_GAME_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GameVersionRecord> getPrimaryKey() {
        return Keys.KEY_GAME_VERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GameVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<GameVersionRecord>>asList(Keys.KEY_GAME_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GameVersionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GameVersionRecord, ?>>asList(Keys.GAME_VERSION_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameVersion as(String alias) {
        return new GameVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameVersion rename(String name) {
        return new GameVersion(name, null);
    }
}
