/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.GameversionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Gameversion extends TableImpl<GameversionRecord> {

    private static final long serialVersionUID = 811825114;

    /**
     * The reference instance of <code>diluv.gameVersion</code>
     */
    public static final Gameversion GAMEVERSION = new Gameversion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameversionRecord> getRecordType() {
        return GameversionRecord.class;
    }

    /**
     * The column <code>diluv.gameVersion.id</code>.
     */
    public final TableField<GameversionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.gameVersion.version</code>.
     */
    public final TableField<GameversionRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>diluv.gameVersion.website</code>.
     */
    public final TableField<GameversionRecord, String> WEBSITE = createField("website", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * The column <code>diluv.gameVersion.createdAt</code>.
     */
    public final TableField<GameversionRecord, Timestamp> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>diluv.gameVersion.gameId</code>.
     */
    public final TableField<GameversionRecord, Long> GAMEID = createField("gameId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.gameVersion</code> table reference
     */
    public Gameversion() {
        this("gameVersion", null);
    }

    /**
     * Create an aliased <code>diluv.gameVersion</code> table reference
     */
    public Gameversion(String alias) {
        this(alias, GAMEVERSION);
    }

    private Gameversion(String alias, Table<GameversionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gameversion(String alias, Table<GameversionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GameversionRecord, Long> getIdentity() {
        return Keys.IDENTITY_GAMEVERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GameversionRecord> getPrimaryKey() {
        return Keys.KEY_GAMEVERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GameversionRecord>> getKeys() {
        return Arrays.<UniqueKey<GameversionRecord>>asList(Keys.KEY_GAMEVERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GameversionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GameversionRecord, ?>>asList(Keys.GAMEVERSION_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Gameversion as(String alias) {
        return new Gameversion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gameversion rename(String name) {
        return new Gameversion(name, null);
    }
}
