/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.ProjectFileGameVersionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileGameVersion extends TableImpl<ProjectFileGameVersionRecord> {

    private static final long serialVersionUID = 1799382126;

    /**
     * The reference instance of <code>diluv.PROJECT_FILE_GAME_VERSION</code>
     */
    public static final ProjectFileGameVersion PROJECT_FILE_GAME_VERSION = new ProjectFileGameVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectFileGameVersionRecord> getRecordType() {
        return ProjectFileGameVersionRecord.class;
    }

    /**
     * The column <code>diluv.PROJECT_FILE_GAME_VERSION.PROJECT_FILE_ID</code>.
     */
    public final TableField<ProjectFileGameVersionRecord, Long> PROJECT_FILE_ID = createField("PROJECT_FILE_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.PROJECT_FILE_GAME_VERSION.PROJECT_VERSION_ID</code>.
     */
    public final TableField<ProjectFileGameVersionRecord, Long> PROJECT_VERSION_ID = createField("PROJECT_VERSION_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.PROJECT_FILE_GAME_VERSION</code> table reference
     */
    public ProjectFileGameVersion() {
        this("PROJECT_FILE_GAME_VERSION", null);
    }

    /**
     * Create an aliased <code>diluv.PROJECT_FILE_GAME_VERSION</code> table reference
     */
    public ProjectFileGameVersion(String alias) {
        this(alias, PROJECT_FILE_GAME_VERSION);
    }

    private ProjectFileGameVersion(String alias, Table<ProjectFileGameVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectFileGameVersion(String alias, Table<ProjectFileGameVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProjectFileGameVersionRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_FILE_GAME_VERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProjectFileGameVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjectFileGameVersionRecord>>asList(Keys.KEY_PROJECT_FILE_GAME_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProjectFileGameVersionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProjectFileGameVersionRecord, ?>>asList(Keys.PROJECT_FILE_GAME_VERSION_IBFK_1, Keys.PROJECT_FILE_GAME_VERSION_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileGameVersion as(String alias) {
        return new ProjectFileGameVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectFileGameVersion rename(String name) {
        return new ProjectFileGameVersion(name, null);
    }
}
