/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.ProjectMemberRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectMember extends TableImpl<ProjectMemberRecord> {

    private static final long serialVersionUID = -109499031;

    /**
     * The reference instance of <code>diluv.PROJECT_MEMBER</code>
     */
    public static final ProjectMember PROJECT_MEMBER = new ProjectMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectMemberRecord> getRecordType() {
        return ProjectMemberRecord.class;
    }

    /**
     * The column <code>diluv.PROJECT_MEMBER.ID</code>.
     */
    public final TableField<ProjectMemberRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.PROJECT_MEMBER.ROLE</code>.
     */
    public final TableField<ProjectMemberRecord, String> ROLE = createField("ROLE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>diluv.PROJECT_MEMBER.PERMISSION</code>.
     */
    public final TableField<ProjectMemberRecord, Integer> PERMISSION = createField("PERMISSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>diluv.PROJECT_MEMBER.CREATED_AT</code>.
     */
    public final TableField<ProjectMemberRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>diluv.PROJECT_MEMBER.PROJECT_ID</code>.
     */
    public final TableField<ProjectMemberRecord, Long> PROJECT_ID = createField("PROJECT_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.PROJECT_MEMBER.USER_ID</code>.
     */
    public final TableField<ProjectMemberRecord, Long> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.PROJECT_MEMBER</code> table reference
     */
    public ProjectMember() {
        this("PROJECT_MEMBER", null);
    }

    /**
     * Create an aliased <code>diluv.PROJECT_MEMBER</code> table reference
     */
    public ProjectMember(String alias) {
        this(alias, PROJECT_MEMBER);
    }

    private ProjectMember(String alias, Table<ProjectMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectMember(String alias, Table<ProjectMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProjectMemberRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROJECT_MEMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProjectMemberRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_MEMBER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProjectMemberRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjectMemberRecord>>asList(Keys.KEY_PROJECT_MEMBER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProjectMemberRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProjectMemberRecord, ?>>asList(Keys.PROJECT_MEMBER_IBFK_2, Keys.PROJECT_MEMBER_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectMember as(String alias) {
        return new ProjectMember(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectMember rename(String name) {
        return new ProjectMember(name, null);
    }
}
