/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables;


import com.diluv.api.models.Diluv;
import com.diluv.api.models.Keys;
import com.diluv.api.models.tables.records.ProjectgameversionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Projectgameversion extends TableImpl<ProjectgameversionRecord> {

    private static final long serialVersionUID = -1085614048;

    /**
     * The reference instance of <code>diluv.projectGameVersion</code>
     */
    public static final Projectgameversion PROJECTGAMEVERSION = new Projectgameversion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectgameversionRecord> getRecordType() {
        return ProjectgameversionRecord.class;
    }

    /**
     * The column <code>diluv.projectGameVersion.projectId</code>.
     */
    public final TableField<ProjectgameversionRecord, Long> PROJECTID = createField("projectId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>diluv.projectGameVersion.projectVersionId</code>.
     */
    public final TableField<ProjectgameversionRecord, Long> PROJECTVERSIONID = createField("projectVersionId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>diluv.projectGameVersion</code> table reference
     */
    public Projectgameversion() {
        this("projectGameVersion", null);
    }

    /**
     * Create an aliased <code>diluv.projectGameVersion</code> table reference
     */
    public Projectgameversion(String alias) {
        this(alias, PROJECTGAMEVERSION);
    }

    private Projectgameversion(String alias, Table<ProjectgameversionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Projectgameversion(String alias, Table<ProjectgameversionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diluv.DILUV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProjectgameversionRecord> getPrimaryKey() {
        return Keys.KEY_PROJECTGAMEVERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProjectgameversionRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjectgameversionRecord>>asList(Keys.KEY_PROJECTGAMEVERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProjectgameversionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProjectgameversionRecord, ?>>asList(Keys.PROJECTGAMEVERSION_IBFK_1, Keys.PROJECTGAMEVERSION_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Projectgameversion as(String alias) {
        return new Projectgameversion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Projectgameversion rename(String name) {
        return new Projectgameversion(name, null);
    }
}
