/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.AnalyticsAuthAccessToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AnalyticsAuthAccessTokenRecord extends UpdatableRecordImpl<AnalyticsAuthAccessTokenRecord> implements Record5<Long, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 533248744;

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.TOKEN</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.TOKEN</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.REFRESH_TOKEN</code>.
     */
    public void setRefreshToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.REFRESH_TOKEN</code>.
     */
    public String getRefreshToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_ACCESS_TOKEN.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN.REFRESH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord value3(String value) {
        setRefreshToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthAccessTokenRecord values(Long value1, String value2, String value3, Timestamp value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnalyticsAuthAccessTokenRecord
     */
    public AnalyticsAuthAccessTokenRecord() {
        super(AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised AnalyticsAuthAccessTokenRecord
     */
    public AnalyticsAuthAccessTokenRecord(Long id, String token, String refreshToken, Timestamp createdAt, Long userId) {
        super(AnalyticsAuthAccessToken.ANALYTICS_AUTH_ACCESS_TOKEN);

        set(0, id);
        set(1, token);
        set(2, refreshToken);
        set(3, createdAt);
        set(4, userId);
    }
}
