/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.AnalyticsAuthMfaToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AnalyticsAuthMfaTokenRecord extends UpdatableRecordImpl<AnalyticsAuthMfaTokenRecord> implements Record4<Long, String, Timestamp, Long> {

    private static final long serialVersionUID = -619177798;

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.TOKEN</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.TOKEN</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.ANALYTICS_AUTH_MFA_TOKEN.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Timestamp, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Timestamp, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaTokenRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaTokenRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaTokenRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnalyticsAuthMfaTokenRecord values(Long value1, String value2, Timestamp value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnalyticsAuthMfaTokenRecord
     */
    public AnalyticsAuthMfaTokenRecord() {
        super(AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN);
    }

    /**
     * Create a detached, initialised AnalyticsAuthMfaTokenRecord
     */
    public AnalyticsAuthMfaTokenRecord(Long id, String token, Timestamp createdAt, Long userId) {
        super(AnalyticsAuthMfaToken.ANALYTICS_AUTH_MFA_TOKEN);

        set(0, id);
        set(1, token);
        set(2, createdAt);
        set(3, userId);
    }
}
