/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.AuthMfaToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthMfaTokenRecord extends UpdatableRecordImpl<AuthMfaTokenRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -355052825;

    /**
     * Setter for <code>diluv.AUTH_MFA_TOKEN.TOKEN</code>.
     */
    public void setToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.AUTH_MFA_TOKEN.TOKEN</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>diluv.AUTH_MFA_TOKEN.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.AUTH_MFA_TOKEN.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AuthMfaToken.AUTH_MFA_TOKEN.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return AuthMfaToken.AUTH_MFA_TOKEN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthMfaTokenRecord value1(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthMfaTokenRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthMfaTokenRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthMfaTokenRecord
     */
    public AuthMfaTokenRecord() {
        super(AuthMfaToken.AUTH_MFA_TOKEN);
    }

    /**
     * Create a detached, initialised AuthMfaTokenRecord
     */
    public AuthMfaTokenRecord(String token, Long userId) {
        super(AuthMfaToken.AUTH_MFA_TOKEN);

        set(0, token);
        set(1, userId);
    }
}
