/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Gameversion;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GameversionRecord extends UpdatableRecordImpl<GameversionRecord> implements Record5<Long, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 187635762;

    /**
     * Setter for <code>diluv.gameVersion.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.gameVersion.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.gameVersion.version</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.gameVersion.version</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.gameVersion.website</code>.
     */
    public void setWebsite(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.gameVersion.website</code>.
     */
    public String getWebsite() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.gameVersion.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.gameVersion.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.gameVersion.gameId</code>.
     */
    public void setGameid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.gameVersion.gameId</code>.
     */
    public Long getGameid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Gameversion.GAMEVERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Gameversion.GAMEVERSION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Gameversion.GAMEVERSION.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Gameversion.GAMEVERSION.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Gameversion.GAMEVERSION.GAMEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord value2(String value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord value3(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord value5(Long value) {
        setGameid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameversionRecord values(Long value1, String value2, String value3, Timestamp value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameversionRecord
     */
    public GameversionRecord() {
        super(Gameversion.GAMEVERSION);
    }

    /**
     * Create a detached, initialised GameversionRecord
     */
    public GameversionRecord(Long id, String version, String website, Timestamp createdat, Long gameid) {
        super(Gameversion.GAMEVERSION);

        set(0, id);
        set(1, version);
        set(2, website);
        set(3, createdat);
        set(4, gameid);
    }
}
