/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projecttypecategory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjecttypecategoryRecord extends UpdatableRecordImpl<ProjecttypecategoryRecord> implements Record5<Long, String, String, String, Long> {

    private static final long serialVersionUID = 138599531;

    /**
     * Setter for <code>diluv.projectTypeCategory.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectTypeCategory.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectTypeCategory.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectTypeCategory.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectTypeCategory.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectTypeCategory.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.projectTypeCategory.slug</code>.
     */
    public void setSlug(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectTypeCategory.slug</code>.
     */
    public String getSlug() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.projectTypeCategory.projectTypeId</code>.
     */
    public void setProjecttypeid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectTypeCategory.projectTypeId</code>.
     */
    public Long getProjecttypeid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projecttypecategory.PROJECTTYPECATEGORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projecttypecategory.PROJECTTYPECATEGORY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Projecttypecategory.PROJECTTYPECATEGORY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Projecttypecategory.PROJECTTYPECATEGORY.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Projecttypecategory.PROJECTTYPECATEGORY.PROJECTTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getProjecttypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord value4(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord value5(Long value) {
        setProjecttypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypecategoryRecord values(Long value1, String value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjecttypecategoryRecord
     */
    public ProjecttypecategoryRecord() {
        super(Projecttypecategory.PROJECTTYPECATEGORY);
    }

    /**
     * Create a detached, initialised ProjecttypecategoryRecord
     */
    public ProjecttypecategoryRecord(Long id, String name, String description, String slug, Long projecttypeid) {
        super(Projecttypecategory.PROJECTTYPECATEGORY);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, slug);
        set(4, projecttypeid);
    }
}
