/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projectmember;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectmemberRecord extends UpdatableRecordImpl<ProjectmemberRecord> implements Record6<Long, String, Long, Timestamp, Long, Long> {

    private static final long serialVersionUID = -1107639889;

    /**
     * Setter for <code>diluv.projectMember.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectMember.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectMember.role</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectMember.role</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectMember.permission</code>.
     */
    public void setPermission(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectMember.permission</code>.
     */
    public Long getPermission() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>diluv.projectMember.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectMember.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.projectMember.projectId</code>.
     */
    public void setProjectid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectMember.projectId</code>.
     */
    public Long getProjectid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.projectMember.userId</code>.
     */
    public void setUserid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.projectMember.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Timestamp, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Timestamp, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projectmember.PROJECTMEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projectmember.PROJECTMEMBER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Projectmember.PROJECTMEMBER.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Projectmember.PROJECTMEMBER.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Projectmember.PROJECTMEMBER.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Projectmember.PROJECTMEMBER.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value2(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value3(Long value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value5(Long value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord value6(Long value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectmemberRecord values(Long value1, String value2, Long value3, Timestamp value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectmemberRecord
     */
    public ProjectmemberRecord() {
        super(Projectmember.PROJECTMEMBER);
    }

    /**
     * Create a detached, initialised ProjectmemberRecord
     */
    public ProjectmemberRecord(Long id, String role, Long permission, Timestamp createdat, Long projectid, Long userid) {
        super(Projectmember.PROJECTMEMBER);

        set(0, id);
        set(1, role);
        set(2, permission);
        set(3, createdat);
        set(4, projectid);
        set(5, userid);
    }
}
