/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectFileProcessing;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileProcessingRecord extends UpdatableRecordImpl<ProjectFileProcessingRecord> implements Record3<Long, String, Timestamp> {

    private static final long serialVersionUID = 1232755195;

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.STARTED_AT</code>.
     */
    public void setStartedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.STARTED_AT</code>.
     */
    public Timestamp getStartedAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.STARTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStartedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value1(Long value) {
        setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value3(Timestamp value) {
        setStartedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord values(Long value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord() {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);
    }

    /**
     * Create a detached, initialised ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord(Long projectFileId, String status, Timestamp startedAt) {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);

        set(0, projectFileId);
        set(1, status);
        set(2, startedAt);
    }
}
