/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectTypePermission;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectTypePermissionRecord extends UpdatableRecordImpl<ProjectTypePermissionRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = -412435982;

    /**
     * Setter for <code>diluv.PROJECT_TYPE_PERMISSION.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE_PERMISSION.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE_PERMISSION.PERMISSION_CREATE</code>.
     */
    public void setPermissionCreate(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE_PERMISSION.PERMISSION_CREATE</code>.
     */
    public Integer getPermissionCreate() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectTypePermission.PROJECT_TYPE_PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProjectTypePermission.PROJECT_TYPE_PERMISSION.PERMISSION_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPermissionCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypePermissionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypePermissionRecord value2(Integer value) {
        setPermissionCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypePermissionRecord values(Long value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectTypePermissionRecord
     */
    public ProjectTypePermissionRecord() {
        super(ProjectTypePermission.PROJECT_TYPE_PERMISSION);
    }

    /**
     * Create a detached, initialised ProjectTypePermissionRecord
     */
    public ProjectTypePermissionRecord(Long id, Integer permissionCreate) {
        super(ProjectTypePermission.PROJECT_TYPE_PERMISSION);

        set(0, id);
        set(1, permissionCreate);
    }
}
