/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projectcomment;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectcommentRecord extends UpdatableRecordImpl<ProjectcommentRecord> implements Record7<Long, String, Timestamp, Timestamp, Long, Long, Long> {

    private static final long serialVersionUID = -1483760628;

    /**
     * Setter for <code>diluv.projectComment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectComment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectComment.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectComment.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectComment.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectComment.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>diluv.projectComment.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectComment.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diluv.projectComment.parentId</code>.
     */
    public void setParentid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectComment.parentId</code>.
     */
    public Long getParentid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.projectComment.projectId</code>.
     */
    public void setProjectid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.projectComment.projectId</code>.
     */
    public Long getProjectid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>diluv.projectComment.userId</code>.
     */
    public void setUserid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.projectComment.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, Timestamp, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, Timestamp, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projectcomment.PROJECTCOMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projectcomment.PROJECTCOMMENT.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Projectcomment.PROJECTCOMMENT.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Projectcomment.PROJECTCOMMENT.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Projectcomment.PROJECTCOMMENT.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Projectcomment.PROJECTCOMMENT.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Projectcomment.PROJECTCOMMENT.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value2(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value3(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value4(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value5(Long value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value6(Long value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord value7(Long value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcommentRecord values(Long value1, String value2, Timestamp value3, Timestamp value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectcommentRecord
     */
    public ProjectcommentRecord() {
        super(Projectcomment.PROJECTCOMMENT);
    }

    /**
     * Create a detached, initialised ProjectcommentRecord
     */
    public ProjectcommentRecord(Long id, String message, Timestamp createdat, Timestamp updatedat, Long parentid, Long projectid, Long userid) {
        super(Projectcomment.PROJECTCOMMENT);

        set(0, id);
        set(1, message);
        set(2, createdat);
        set(3, updatedat);
        set(4, parentid);
        set(5, projectid);
        set(6, userid);
    }
}
