/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectType;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectTypeRecord extends UpdatableRecordImpl<ProjectTypeRecord> implements Record6<Long, String, String, String, Long, Long> {

    private static final long serialVersionUID = 524081602;

    /**
     * Setter for <code>diluv.PROJECT_TYPE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE.SLUG</code>.
     */
    public void setSlug(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.SLUG</code>.
     */
    public String getSlug() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE.MAX_BYTE_SIZE</code>.
     */
    public void setMaxByteSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.MAX_BYTE_SIZE</code>.
     */
    public Long getMaxByteSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT_TYPE.GAME_ID</code>.
     */
    public void setGameId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_TYPE.GAME_ID</code>.
     */
    public Long getGameId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectType.PROJECT_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectType.PROJECT_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProjectType.PROJECT_TYPE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProjectType.PROJECT_TYPE.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProjectType.PROJECT_TYPE.MAX_BYTE_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ProjectType.PROJECT_TYPE.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getMaxByteSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value4(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value5(Long value) {
        setMaxByteSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord value6(Long value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectTypeRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectTypeRecord
     */
    public ProjectTypeRecord() {
        super(ProjectType.PROJECT_TYPE);
    }

    /**
     * Create a detached, initialised ProjectTypeRecord
     */
    public ProjectTypeRecord(Long id, String name, String description, String slug, Long maxByteSize, Long gameId) {
        super(ProjectType.PROJECT_TYPE);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, slug);
        set(4, maxByteSize);
        set(5, gameId);
    }
}
