/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projectcategory;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectcategoryRecord extends UpdatableRecordImpl<ProjectcategoryRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -7319200;

    /**
     * Setter for <code>diluv.projectCategory.projectId</code>.
     */
    public void setProjectid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectCategory.projectId</code>.
     */
    public Long getProjectid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectCategory.projectTypeCategoryId</code>.
     */
    public void setProjecttypecategoryid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectCategory.projectTypeCategoryId</code>.
     */
    public Long getProjecttypecategoryid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projectcategory.PROJECTCATEGORY.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Projectcategory.PROJECTCATEGORY.PROJECTTYPECATEGORYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getProjecttypecategoryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcategoryRecord value1(Long value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcategoryRecord value2(Long value) {
        setProjecttypecategoryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectcategoryRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectcategoryRecord
     */
    public ProjectcategoryRecord() {
        super(Projectcategory.PROJECTCATEGORY);
    }

    /**
     * Create a detached, initialised ProjectcategoryRecord
     */
    public ProjectcategoryRecord(Long projectid, Long projecttypecategoryid) {
        super(Projectcategory.PROJECTCATEGORY);

        set(0, projectid);
        set(1, projecttypecategoryid);
    }
}
