/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectFileDownload;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileDownloadRecord extends UpdatableRecordImpl<ProjectFileDownloadRecord> implements Record3<Long, String, Timestamp> {

    private static final long serialVersionUID = 82449654;

    /**
     * Setter for <code>diluv.PROJECT_FILE_DOWNLOAD.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_DOWNLOAD.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_DOWNLOAD.IP</code>.
     */
    public void setIp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_DOWNLOAD.IP</code>.
     */
    public String getIp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_DOWNLOAD.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_DOWNLOAD.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFileDownload.PROJECT_FILE_DOWNLOAD.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectFileDownload.PROJECT_FILE_DOWNLOAD.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ProjectFileDownload.PROJECT_FILE_DOWNLOAD.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileDownloadRecord value1(Long value) {
        setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileDownloadRecord value2(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileDownloadRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileDownloadRecord values(Long value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileDownloadRecord
     */
    public ProjectFileDownloadRecord() {
        super(ProjectFileDownload.PROJECT_FILE_DOWNLOAD);
    }

    /**
     * Create a detached, initialised ProjectFileDownloadRecord
     */
    public ProjectFileDownloadRecord(Long projectFileId, String ip, Timestamp createdAt) {
        super(ProjectFileDownload.PROJECT_FILE_DOWNLOAD);

        set(0, projectFileId);
        set(1, ip);
        set(2, createdAt);
    }
}
