/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Project;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record12<Long, String, String, String, String, String, Long, Boolean, Timestamp, Timestamp, Long, Long> {

    private static final long serialVersionUID = -153898450;

    /**
     * Setter for <code>diluv.project.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.project.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.project.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.project.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.project.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.project.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.project.shortDescription</code>.
     */
    public void setShortdescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.project.shortDescription</code>.
     */
    public String getShortdescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.project.slug</code>.
     */
    public void setSlug(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.project.slug</code>.
     */
    public String getSlug() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diluv.project.logo</code>.
     */
    public void setLogo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.project.logo</code>.
     */
    public String getLogo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>diluv.project.totalDownloads</code>.
     */
    public void setTotaldownloads(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.project.totalDownloads</code>.
     */
    public Long getTotaldownloads() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>diluv.project.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>diluv.project.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>diluv.project.updatedAt</code>.
     */
    public void setUpdatedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>diluv.project.updatedAt</code>.
     */
    public Timestamp getUpdatedat() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>diluv.project.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>diluv.project.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>diluv.project.projectTypeId</code>.
     */
    public void setProjecttypeid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>diluv.project.projectTypeId</code>.
     */
    public Long getProjecttypeid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>diluv.project.userId</code>.
     */
    public void setUserid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>diluv.project.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Long, Boolean, Timestamp, Timestamp, Long, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Long, Boolean, Timestamp, Timestamp, Long, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Project.PROJECT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Project.PROJECT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Project.PROJECT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Project.PROJECT.SHORTDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Project.PROJECT.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Project.PROJECT.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Project.PROJECT.TOTALDOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Project.PROJECT.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Project.PROJECT.UPDATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Project.PROJECT.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Project.PROJECT.PROJECTTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Project.PROJECT.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getShortdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getTotaldownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getProjecttypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value4(String value) {
        setShortdescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value5(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value6(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value7(Long value) {
        setTotaldownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value8(Boolean value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value9(Timestamp value) {
        setUpdatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value10(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value11(Long value) {
        setProjecttypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value12(Long value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7, Boolean value8, Timestamp value9, Timestamp value10, Long value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Long id, String name, String description, String shortdescription, String slug, String logo, Long totaldownloads, Boolean deleted, Timestamp updatedat, Timestamp createdat, Long projecttypeid, Long userid) {
        super(Project.PROJECT);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, shortdescription);
        set(4, slug);
        set(5, logo);
        set(6, totaldownloads);
        set(7, deleted);
        set(8, updatedat);
        set(9, createdat);
        set(10, projecttypeid);
        set(11, userid);
    }
}
