/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.ProjectFileProcessingLog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileProcessingLogRecord extends UpdatableRecordImpl<ProjectFileProcessingLogRecord> implements Record4<Long, Integer, String, Timestamp> {

    private static final long serialVersionUID = -158223662;

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.STATUS_ID</code>.
     */
    public void setStatusId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.STATUS_ID</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.LOGS</code>.
     */
    public void setLogs(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.LOGS</code>.
     */
    public String getLogs() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING_LOG.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Integer, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG.LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLogs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingLogRecord value1(Long value) {
        setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingLogRecord value2(Integer value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingLogRecord value3(String value) {
        setLogs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingLogRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingLogRecord values(Long value1, Integer value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileProcessingLogRecord
     */
    public ProjectFileProcessingLogRecord() {
        super(ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG);
    }

    /**
     * Create a detached, initialised ProjectFileProcessingLogRecord
     */
    public ProjectFileProcessingLogRecord(Long projectFileId, Integer statusId, String logs, Timestamp createdAt) {
        super(ProjectFileProcessingLog.PROJECT_FILE_PROCESSING_LOG);

        set(0, projectFileId);
        set(1, statusId);
        set(2, logs);
        set(3, createdAt);
    }
}
