/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projectfile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectfileRecord extends UpdatableRecordImpl<ProjectfileRecord> implements Record10<Long, String, String, Long, String, String, Long, Timestamp, Long, Long> {

    private static final long serialVersionUID = 1742044084;

    /**
     * Setter for <code>diluv.projectFile.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectFile.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectFile.sha256</code>.
     */
    public void setSha256(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectFile.sha256</code>.
     */
    public String getSha256() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectFile.fileName</code>.
     */
    public void setFilename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectFile.fileName</code>.
     */
    public String getFilename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.projectFile.size</code>.
     */
    public void setSize(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectFile.size</code>.
     */
    public Long getSize() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>diluv.projectFile.releaseType</code>.
     */
    public void setReleasetype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectFile.releaseType</code>.
     */
    public String getReleasetype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diluv.projectFile.displayName</code>.
     */
    public void setDisplayname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.projectFile.displayName</code>.
     */
    public String getDisplayname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>diluv.projectFile.downloads</code>.
     */
    public void setDownloads(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.projectFile.downloads</code>.
     */
    public Long getDownloads() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>diluv.projectFile.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>diluv.projectFile.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>diluv.projectFile.parentId</code>.
     */
    public void setParentid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>diluv.projectFile.parentId</code>.
     */
    public Long getParentid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>diluv.projectFile.projectId</code>.
     */
    public void setProjectid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>diluv.projectFile.projectId</code>.
     */
    public Long getProjectid() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Long, String, String, Long, Timestamp, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Long, String, String, Long, Timestamp, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projectfile.PROJECTFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projectfile.PROJECTFILE.SHA256;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Projectfile.PROJECTFILE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Projectfile.PROJECTFILE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Projectfile.PROJECTFILE.RELEASETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Projectfile.PROJECTFILE.DISPLAYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Projectfile.PROJECTFILE.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Projectfile.PROJECTFILE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Projectfile.PROJECTFILE.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Projectfile.PROJECTFILE.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSha256();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReleasetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDisplayname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value2(String value) {
        setSha256(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value3(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value4(Long value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value5(String value) {
        setReleasetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value6(String value) {
        setDisplayname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value7(Long value) {
        setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value8(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value9(Long value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value10(Long value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord values(Long value1, String value2, String value3, Long value4, String value5, String value6, Long value7, Timestamp value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectfileRecord
     */
    public ProjectfileRecord() {
        super(Projectfile.PROJECTFILE);
    }

    /**
     * Create a detached, initialised ProjectfileRecord
     */
    public ProjectfileRecord(Long id, String sha256, String filename, Long size, String releasetype, String displayname, Long downloads, Timestamp createdat, Long parentid, Long projectid) {
        super(Projectfile.PROJECTFILE);

        set(0, id);
        set(1, sha256);
        set(2, filename);
        set(3, size);
        set(4, releasetype);
        set(5, displayname);
        set(6, downloads);
        set(7, createdat);
        set(8, parentid);
        set(9, projectid);
    }
}
