/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projectfile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectfileRecord extends UpdatableRecordImpl<ProjectfileRecord> implements Record12<Long, String, String, String, Long, Long, String, String, Timestamp, Long, Long, Long> {

    private static final long serialVersionUID = 1136520234;

    /**
     * Setter for <code>diluv.projectFile.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectFile.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectFile.sha256</code>.
     */
    public void setSha256(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectFile.sha256</code>.
     */
    public String getSha256() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectFile.fileName</code>.
     */
    public void setFilename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectFile.fileName</code>.
     */
    public String getFilename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.projectFile.displayName</code>.
     */
    public void setDisplayname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectFile.displayName</code>.
     */
    public String getDisplayname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.projectFile.size</code>.
     */
    public void setSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectFile.size</code>.
     */
    public Long getSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.projectFile.downloads</code>.
     */
    public void setDownloads(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.projectFile.downloads</code>.
     */
    public Long getDownloads() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>diluv.projectFile.releaseType</code>.
     */
    public void setReleasetype(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.projectFile.releaseType</code>.
     */
    public String getReleasetype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>diluv.projectFile.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>diluv.projectFile.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>diluv.projectFile.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>diluv.projectFile.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>diluv.projectFile.parentId</code>.
     */
    public void setParentid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>diluv.projectFile.parentId</code>.
     */
    public Long getParentid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>diluv.projectFile.projectId</code>.
     */
    public void setProjectid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>diluv.projectFile.projectId</code>.
     */
    public Long getProjectid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>diluv.projectFile.userId</code>.
     */
    public void setUserid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>diluv.projectFile.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, Long, Long, String, String, Timestamp, Long, Long, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, Long, Long, String, String, Timestamp, Long, Long, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projectfile.PROJECTFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projectfile.PROJECTFILE.SHA256;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Projectfile.PROJECTFILE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Projectfile.PROJECTFILE.DISPLAYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Projectfile.PROJECTFILE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Projectfile.PROJECTFILE.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Projectfile.PROJECTFILE.RELEASETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Projectfile.PROJECTFILE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Projectfile.PROJECTFILE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Projectfile.PROJECTFILE.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Projectfile.PROJECTFILE.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Projectfile.PROJECTFILE.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSha256();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplayname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getReleasetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value2(String value) {
        setSha256(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value3(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value4(String value) {
        setDisplayname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value5(Long value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value6(Long value) {
        setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value7(String value) {
        setReleasetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value8(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value9(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value10(Long value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value11(Long value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord value12(Long value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectfileRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, String value7, String value8, Timestamp value9, Long value10, Long value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectfileRecord
     */
    public ProjectfileRecord() {
        super(Projectfile.PROJECTFILE);
    }

    /**
     * Create a detached, initialised ProjectfileRecord
     */
    public ProjectfileRecord(Long id, String sha256, String filename, String displayname, Long size, Long downloads, String releasetype, String status, Timestamp createdat, Long parentid, Long projectid, Long userid) {
        super(Projectfile.PROJECTFILE);

        set(0, id);
        set(1, sha256);
        set(2, filename);
        set(3, displayname);
        set(4, size);
        set(5, downloads);
        set(6, releasetype);
        set(7, status);
        set(8, createdat);
        set(9, parentid);
        set(10, projectid);
        set(11, userid);
    }
}
