/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.Projecttype;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjecttypeRecord extends UpdatableRecordImpl<ProjecttypeRecord> implements Record6<Long, String, String, String, Long, Long> {

    private static final long serialVersionUID = -1768222323;

    /**
     * Setter for <code>diluv.projectType.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.projectType.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.projectType.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.projectType.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.projectType.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.projectType.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.projectType.slug</code>.
     */
    public void setSlug(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.projectType.slug</code>.
     */
    public String getSlug() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.projectType.maxByteSize</code>.
     */
    public void setMaxbytesize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.projectType.maxByteSize</code>.
     */
    public Long getMaxbytesize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.projectType.gameId</code>.
     */
    public void setGameid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.projectType.gameId</code>.
     */
    public Long getGameid() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Projecttype.PROJECTTYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projecttype.PROJECTTYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Projecttype.PROJECTTYPE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Projecttype.PROJECTTYPE.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Projecttype.PROJECTTYPE.MAXBYTESIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Projecttype.PROJECTTYPE.GAMEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getMaxbytesize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value4(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value5(Long value) {
        setMaxbytesize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord value6(Long value) {
        setGameid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjecttypeRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjecttypeRecord
     */
    public ProjecttypeRecord() {
        super(Projecttype.PROJECTTYPE);
    }

    /**
     * Create a detached, initialised ProjecttypeRecord
     */
    public ProjecttypeRecord(Long id, String name, String description, String slug, Long maxbytesize, Long gameid) {
        super(Projecttype.PROJECTTYPE);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, slug);
        set(4, maxbytesize);
        set(5, gameid);
    }
}
