/*
 * This file is generated by jOOQ.
*/
package com.diluv.api.models.tables.records;


import com.diluv.api.models.tables.User;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record12<Long, String, String, String, String, Boolean, Boolean, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -2033194718;

    /**
     * Setter for <code>diluv.user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diluv.user.verifiedEmail</code>.
     */
    public void setVerifiedemail(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.user.verifiedEmail</code>.
     */
    public Boolean getVerifiedemail() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>diluv.user.mfaEnabled</code>.
     */
    public void setMfaenabled(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.user.mfaEnabled</code>.
     */
    public Boolean getMfaenabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>diluv.user.location</code>.
     */
    public void setLocation(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>diluv.user.location</code>.
     */
    public String getLocation() {
        return (String) get(7);
    }

    /**
     * Setter for <code>diluv.user.firstName</code>.
     */
    public void setFirstname(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>diluv.user.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>diluv.user.lastName</code>.
     */
    public void setLastname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>diluv.user.lastName</code>.
     */
    public String getLastname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>diluv.user.mfaSecret</code>.
     */
    public void setMfasecret(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>diluv.user.mfaSecret</code>.
     */
    public String getMfasecret() {
        return (String) get(10);
    }

    /**
     * Setter for <code>diluv.user.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>diluv.user.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, Boolean, Boolean, String, String, String, String, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, Boolean, Boolean, String, String, String, String, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return User.USER.VERIFIEDEMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return User.USER.MFAENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return User.USER.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return User.USER.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return User.USER.MFASECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return User.USER.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getVerifiedemail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getMfaenabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMfasecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(Boolean value) {
        setVerifiedemail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Boolean value) {
        setMfaenabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(String value) {
        setMfasecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, String value5, Boolean value6, Boolean value7, String value8, String value9, String value10, String value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String email, String username, String password, String avatar, Boolean verifiedemail, Boolean mfaenabled, String location, String firstname, String lastname, String mfasecret, Timestamp createdat) {
        super(User.USER);

        set(0, id);
        set(1, email);
        set(2, username);
        set(3, password);
        set(4, avatar);
        set(5, verifiedemail);
        set(6, mfaenabled);
        set(7, location);
        set(8, firstname);
        set(9, lastname);
        set(10, mfasecret);
        set(11, createdat);
    }
}
